name: CD
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout Git Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          cache: 'maven'

      - name: Build with Maven
        run: mvn package

      - name: build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with: 
          username: rodrigospimenta
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: rodrigospimenta/myapp
          tags: ${{ github.sha }}, latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build
    steps:

      - name: Checkout Git Code
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: update k8s
        run: |
          cd k8s
          kustomize edit set image myapp=rodrigospimenta/myapp:${{ github.sha }}
          cat kustomization.yaml

      - name: commit own repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "change image tag"

      - name: push own repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SSH_CD }}
          branch: main


